INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1'', ''fa fa-send-o'', ''敏捷开发'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1_1'', ''fa fa-desktop'', ''代码生成器'', ''pages/1.html'',''1'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1_2'', ''fa fa-search'', ''单页管理'', ''pages/1.html'',''1'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1_3'', ''fa fa-send-o'', ''插件演示'', ''pages/1.html'' ,''1'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1_4'', ''fa fa-window-restore'', ''开发示例'','''',''1'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''1_4_1'', ''fa fa-assistive-listening-systems'', ''商机管理'' , ''pages/1.html'',''1_4'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''khgl'', ''fa fa-vcard'', ''客户管理'', ''pages/1.html'' ,'''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''kpxx'', ''fa fa-file-excel-o'', ''开票信息'' , ''pages/1.html'','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''khdd'', ''fa fa-modx'', ''客户订单'' , ''pages/1.html'','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xtgl'', ''fa fa-desktop'', ''系统管理'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xzgl'', ''fa fa-leaf'', ''行政管理'', ''pages/1.html'' ,''xzgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjzd'', ''fa fa-book'', ''数据字典'', ''pages/1.html'',''xzgl'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''djbm'', ''fa fa-barcode'', ''单据编码'', ''pages/1.html'' ,''xzgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xtgn'', ''fa fa-navicon'', ''系统功能'', ''pages/1.html'' ,''xzgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''excel'', ''fa fa-file-excel-o'', ''Excel配置'','''',''xzgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''drpz'', ''fa fa-sign-out'', ''导入配置'', ''pages/1.html'',''excel'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''dcpz'', ''fa fa-sign-out'', ''导出配置'', ''pages/1.html'',''excel'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjgl'', ''fa fa-database'', ''数据管理'','''',''xzgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjklj'', ''fa fa-plug'', ''数据库连接'', ''pages/1.html'' ,''sjgl'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjbgl'', ''fa fa-table'', ''数据表管理'', ''pages/1.html''  ,''sjgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjygl'', ''fa fa-bullseye'', ''数据源管理'', ''pages/1.html''  ,''sjgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xtrz'', ''fa fa-warning'', ''系统日志'' ,'''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sjqxgl'', ''fa fa-briefcase'', ''数据权限管理'' ,'''','''' );
INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''dwzz'', ''fa fa-coffee'', ''单位组织'' ,'''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''gsgl'', ''fa fa-sitemap'', ''公司管理'', ''pages/1.html'' ,''dwzz'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bmgl'', ''fa fa-th-list'', ''部门管理'', ''pages/1.html'',''dwzz'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''gwgl'', ''fa fa-graduation-cap'', ''岗位管理'', ''pages/1.html'' ,''dwzz'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''jsgl'', ''fa fa-paw'', ''角色管理'', ''pages/1.html'',''dwzz'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''yhgl'', ''fa fa-user'', ''用户管理'', ''pages/1.html'' ,''dwzz'');
INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bdzx'', ''fa fa-table'', ''表单中心'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''zdybd'', ''fa fa-puzzle-piece'', ''自定义表单'', ''pages/1.html'' ,''bdzx'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''fbbdgn'', ''fa fa-list-alt'', ''发布表单功能'', ''pages/1.html'' ,''bdzx''  );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bdfbsl'', ''fa fa-list-alt'', ''表单发布实例'','''',''bdzx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''hyda'', ''fa fa-address-card-o'', ''会员档案'', ''pages/1.html'' ,''bdfbsl'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''ddgn'', ''fa fa-address-book'', ''订单功能'', ''pages/1.html'',''bdfbsl'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''qjgl'', ''fa fa-user-circle'', ''请假管理'', ''pages/1.html'',''bdfbsl'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''csbd'', ''fa fa-bandcamp'', ''测试表单'', ''pages/1.html'' ,''bdfbsl'');
INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''lczx'', ''fa fa-share-alt'', ''流程中心'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''mbgl'', ''fa fa-share-alt'', ''模板管理'', ''pages/1.html'' ,''lczx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''wdrw'', ''fa fa-file-word-o'', ''我的任务'', ''pages/1.html''  ,''lczx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''gzwt'', ''fa fa-coffee'', ''工作委托'', ''pages/1.html''  ,''lczx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''lcjk'', ''fa fa-eye'', ''流程监控'', ''pages/1.html'' ,''lczx'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xtlcgl'', ''fa fa-industry'', ''系统流程案例'', ''pages/1.html'' ,''lczx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bbzx'', ''fa fa-area-chart'', ''报表中心'','''','''' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bbgl'', ''fa fa-cogs'', ''报表管理'', ''pages/1.html'' ,''bbzx'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bbsl'', ''fa fa-file-powerpoint-o'', ''报表实例'','''',''bbzx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xstb'', ''fa fa-area-chart'', ''销售图表'', ''pages/1.html'' ,''bbsl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xslb'', ''fa fa-area-chart'', ''销售列表'', ''pages/1.html'',''bbsl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xshh'', ''fa fa-area-chart'', ''销售混合'', ''pages/1.html'' ,''bbsl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''bbxq'', ''fa fa-wpforms'', ''报表模板'','''',''bbzx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''cgbb'', ''fa fa-bar-chart'', ''采购报表'', ''pages/1.html'' ,''bbxq'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''sxbb'', ''fa fa-line-chart'', ''销售报表'', ''pages/1.html'' ,''bbxq'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''ccbb'', ''fa fa-area-chart'', ''仓存报表'', ''pages/1.html'' ,''bbxq'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''szbb'', ''fa fa-pie-chart'', ''收支报表'', ''pages/1.html''  ,''bbxq'');
INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''ggxx'', ''fa fa-globe'', ''公共信息'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''xwzx'', ''fa-feed'', ''新闻中心'', ''pages/1.html''  ,''ggxx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''khxq1'', ''fa-braille'', ''客户详情'', ''pages/1.html'',''ggxx'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''tzgg'', ''fa fa-volume-up'', ''通知公告'', ''pages/1.html'' ,''ggxx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''wjzl'', ''fa fa-jsfiddle'', ''文件资料'', ''pages/1.html'' ,''ggxx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''rcgl'', ''fa fa-calendar'', ''日程管理'', ''pages/1.html'' ,''ggxx'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''yjzx'', ''fa fa-send'', ''邮件中心'', ''pages/1.html'',''ggxx'' );
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''dzqz'', ''fa fa-registered'', ''电子签章'', ''pages/1.html'' ,''ggxx'');
INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''ydgl'', ''fa fa-android'', ''移动管理'','''','''');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''wxgl'', ''fa fa-weixin'', ''微信管理'','' '',''ydgl'');
 INSERT INTO sys_menu (menu_id,icon_cls,menu_name, menu_url, parent_menu_id) VALUES (  ''qyhsz'', ''fa fa-plug'', ''企业号设置'', ''pages/1.html'' ,''wxgl'');